- src/calendar/calendar.css
- src/calendar/calendar.html
- src/dailyLog/dailyLog.css
- src/dailyLog/index.html
> Styling for daily Log and calendar

- src/dailyLog/index.html
- src/navbar/navbar.css
#9 fixed link to stylesheet
#9 removed extra buttons 
#19 fixed the font
> Fixed stylesheet link and minor style issues

- src/calendar/calendar.css
Changes:
In calendar.css, I removed this line, `background-color: var(--calendar-background-color);`, from 
```/* Calendar border */
.calendar-table th,
.calendar-table td {}
> #62 Fixed the Days of the Week Coloring

- docs/adr/051224-Database-LocalStorage.md
- docs/adr/051224-Gihub-Projects.md
- docs/adr/051724-Markdown-Functionality.md
This is migrating the ADRs we had in our main repo into this repo.
> Adr documentation

- src/navbar/navbar.css
- src/navbar/navbar.html
added correct link to accomplishments page in navbar
> added accomplishments page to navbar

- src/settings/settings.css
- src/settings/settings.html
added a boilerplate for settings, and added styling adhering to style guide with no magic numbers, and added navbar addresses #68
> Settings page boilerplate and styling

- src/navbar/navbar.html
- src/settings/settings.html
#19 adds settings page to navbar, also adds main to settings page for navbar
> Adds settings page to navbar

- docs/adr/053024-Style-Guide.md
#66 - Wrote reasonings behind the style guide, including branding, icons, typography, colors, and more.
> #66 - Added style guide ADR

- src/assets/icons/check-icon.svg
> Added checkmark icon

- src/notes/note-element.js
> #100 fixes bug of text not wrapping for long strings in notes

- docs/adr/053024-Style-Guide.md
- src/accomplishments/accomplishments.html
- src/calendar/calendar.html
- src/dailyLog/index.html
- src/navbar/navbar.html
- src/navbar/navbar.js
- src/notes/notes.html
- src/password/landing.js
- src/settings/settings.html
- src/settings/settings.js
Anything that was changed that isn't a path was because they were old files that got added by people who hadn't set up Prettier yet, so Prettier fixed the formatting when I edited them.
> Update non relative paths

- src/backend-storage/records-api.js
- src/calendar/calendar.js
- src/dailyLog/simpleMDE.js
Fixes almost all failing files in the linter. simpleMDE will still fail on the simpleMDE being undefined. However, once Sravya switches it to be downloaded in the repo and required in the JS rather than a script linking to the online version, it should go away.
> Fix failing files

- src/backend-storage/records-api.js
- src/calendar/calendar.js
- src/dailyLog/simpleMDE.js
- src/password/landing.js
- src/settings/settings.html
- src/settings/settings.js
> Password boilerplate html

- src/calendar/calendar.css
- src/notes/notes.css
I implemented variables for all values and omitted any "magic numbers". I also changed the order of the code based on the style specificity.
> Cleaning Notes.CSS for Issue #121

- src/index.html
- src/index.js
things automatically look for an index.html as a starting page (even liveserver). I added that index.html page that automatically redirects to another file, in this case calendar.html, but once issue #114 is finished, it should be updated to landing.html.
> added index file that automatically redirects for hosting app

- src/accomplishments/accomplishments.html
> #135 fix faulty link to js file in accomplishments.html

- src/navbar/navbar.js
Edited navbar.js to adhere to code styling guidelines
> 122: updated navbar.js for code styling

- src/backend-storage/accomplishments-api.js
- src/dailyLog/simpleMDE.js
- src/notes/notes.js
Part of #122 , cleaned up JavaScript files assigned to Daniel Luo
> Issue #122 JavaScript Cleanup for files accomplishments-api.js, notes.js, and simpleMDE.js

- docs/adr/060324-Cloudflare.md
Add ADR for using cloudflare for deployment
> Create 060324-Cloudflare.md ADR

- src/accomplishments/accomplishments.css
- src/accomplishments/accomplishments.html
- Cleaned up the CSS for the Accomplishments page for Issue #121 
- Fixed the Styling for the Accomplishments page for Issue #141
> Accomplishments styling

- src/password/landing.css
for issue #121 , was having issues with other pr so I made a new one. 
I added more descriptive comments to each tag and made variables for all numbers. 
Please lmk if I should add/take out anything.
> landing css cleanup (new)

- .github/workflows/deploydocs.yml
Adding JSDocs Building where:
Files Checked Out
JSDocs Action Runs
Upload to cloudflare where it can be found here: https://docs-dev-journal.pages.dev/
> Add js docs building

- src/dailyLog/index.html
- src/navbar/navbar.html
I added comments and styled this html file according to the instructions listed in issue #119
> Style navbar html #119

- src/backend-storage/accomplishments-class.js
- src/calendar/calendar.js
- src/settings/settings.js
For issue #122
Cleaned up (and in JSDocs format):
Calendar.js
accomplishments-class.js
settings.js
Note I had a merge in from `dev`, which is why I have other files in the commit.
> #122 Javascript Cleanup

- src/settings/settings.css
#121 - Put all values into CSS variables for clarity and consistency with Brooke and Shambhavi. Also added media tags to make the form responsive. Changed ordering of elements in CSS to match its weights.
> Cleaned settings.css and added media tags for responsiveness

- src/dailyLog/simpleMDE.js
Removed features from the simple mde toolbars so that resizing looks better.
> Edited toolbar to remove unnecessary features

- src/notes/notes.html
- src/password/landing.html
- src/password/landing.js
- src/settings/settings.html
- src/settings/settings.js
#119 html cleanup for landing, settings, notes
Adds relative links from landing/settings to calendar page for deployment
> Cleans HTML, fixes relative links for landing/settings

- src/backend-storage/mde-mode-api.js
- src/dailyLog/simpleMDE.js
- src/settings/settings.html
- src/settings/settings.js
Ravi and I implemented a new button in the settings page that enables/disables the MDE for Daily Logs.
> Optional MDE for Issue #110

- src/accomplishments/accomplishments-helpers.js
- src/accomplishments/accomplishments.css
- src/accomplishments/accomplishments.html
- src/calendar/calendar.css
- src/calendar/calendar.html
- src/dailyLog/dailyLog.css
- src/dailyLog/index.html
- src/index.css
- src/index.html
- src/notes/notes.css
- src/notes/notes.html
- src/password/landing.css
- src/password/landing.html
- src/settings/settings.css
- src/settings/settings.html
- test/end-to-end/daily-log.test.js
Re-creating this PR into dev instead of main
> Add noscript tags

- src/backend-storage/record-class.js
- src/notes/notes.js
Edited notes.js and record-class.js in order to comply to the code style guide.
> fixes #122 - edited notes.js and record-class.js

- src/dailyLog/dailyLog.css
- src/settings/settings.css
- src/settings/settings.html
Please merge this only after PR#182 is merged.
> Fix css issues

- src/calendar/calendar.js
- src/notes/notes.js
- src/settings/settings.js
Final PR into dev before PRing dev into main
> Notes bug fixes
